### PR TITLE
make icons look better

### PR DESCRIPTION
**Pull request by adk7712**

### CODE REVIEW

**Review by adk7712 — COMMENTED** [review]
as requested

**Comment by sciencepal** [comment]
Sorry, can you remove lines 58 - 78 ... they are taken from a python code.

**Comment by adk7712** [comment]
> Sorry, can you remove lines 58 - 78 ... they are taken from a python code.

Hey there! I have removed the requested lines!

**Comment by sciencepal** [comment]
oops, looks like you removed a newline at the end

**Comment by adk7712** [comment]
> oops, looks like you removed a newline at the end

there! I have added a newline to the end of the file.

**Pull request merged**
